### PR TITLE
Add recent updates

### PR DESCRIPTION
**Pull request by hobywan**
It is required to fix the outdated submodule in Wonton.
@raovgarimella @angelaherring @nray @ekikinzon @velecjan @lipnikov

### CODE REVIEW

**Comment by raovgarimella** [comment]
squash commit history please. Also, why is it showing 28 files changed if only r3d submodule is being updated?

**Comment by hobywan** [comment]
Is it necessary to squash commits here?
Those commits are mirrored from [devonmpowell/r3d.git](https://github.com/devonmpowell/r3d/commits/master) which are already *public*.
I can always squash them prior to merge.

> Also, why is it showing 28 files changed if only r3d submodule is being updated
This is *R3D* not Wonton.
It is not a submodule, and the last update was last year.

**Comment by hobywan** [comment]
Is it necessary to squash commits here?
Those commits are mirrored from devonmpowell/r3d.git which are already **public**.
I can always squash them prior to merge.

> Also, why is it showing 28 files changed if only r3d submodule is being updated?

This is **R3D** not Wonton.
It is not a submodule, and the last update was last year.

**Comment by raovgarimella** [comment]
Ah. Sorry for my inattention. No you don't have to squash or do anything else.

**Comment by hobywan** [comment]
Great. If you have the necessary permissions, could you please approve/merge it so that I can update the submodule in Wonton?

**Comment by raovgarimella** [comment]
I don't. You should ping @angelaherring or Chris Malone

**Comment by hobywan** [comment]
@angelaherring @cmsquared 
Could one of you please review this pull request at your convenience?
It is required to fix the outdated submodule in Wonton.
Thanks!

**Comment by cmsquared** [comment]
I don't have write access, and I'm not sure who does.  Maybe @ddaniel if @angelaherring doesn't.

**Comment by ddaniel** [comment]
Made @cmsquared an owner

**Comment by hobywan** [comment]
Thanks!

**Comment by hobywan** [comment]
Thanks!
@cmsquared Would you mind merging it at your convenience?

**Comment by cmsquared** [comment]
> Thanks!
> @cmsquared Would you mind merging it at your convenience?

Sorry for not responding - glad Angela took care of it!

**Pull request merged**
